name: Generate Android Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -alias ${{ secrets.ANDROID_KEY_ALIAS }} \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass ${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.ANDROID_KEY_PASSWORD }} \
            -dname "CN=Florian, OU=Dev, O=Florian, L=France, S=France, C=FR" \
            -keystore my-release-key.keystore

      - name: Encode keystore to base64
        run: |
          base64 my-release-key.keystore > keystore.b64

      - name: Upload keystore artifact
        uses: actions/upload-artifact@v4
        with:
          name: keystore-base64
          path: keystore.b64
